### ISSUE TITLE
삭제 관련 버그

### ISSUE THREAD

**Issue by hongji3354** [woochanleee/project-tree-generator#2]
![screencast 2021-08-12 12-49-06](https://user-images.githubusercontent.com/57903576/129135616-56512f2f-07f0-4361-9cef-82467ee0f21b.gif)

**Comment by woochanleee** [comment]
@hongji3354 어느 부분이 버그 처럼 동작하는지 설명 가능할까요!?

**Comment by hongji3354** [comment]
@woochanleee 아 내용이 누락됐군요. 죄송합니다.

이미지 보시면 second 안에 folder 삭제시 second와 같은 level에 있는 third의 폴더명이 한글자씩 사라지는 버그 입니다!

**Comment by woochanleee** [comment]
@hongji3354 앗 그렇네요! 제보해주셔서 감사합니다 :)
